package com.client.commande.ClientCommandeGestion.entity;
// Generated 4 juil. 2017 15:35:42 by Hibernate Tools 5.2.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Client generated by hbm2java
 */
@Entity
@Table( name = "client", catalog = "mybdd" )
public class Client implements java.io.Serializable {

    private Integer       id;
    private String        nom;
    private String        prenom;
    private String        adresse;
    private String        telephone;
    private String        email;
    private String        image;
    private Set<Commande> commandes = new HashSet<Commande>( 0 );

    public Client() {
    }

    public Client( String nom, String adresse, String telephone ) {
        this.nom = nom;
        this.adresse = adresse;
        this.telephone = telephone;
    }

    public Client( String nom, String prenom, String adresse, String telephone, String email, String image,
            Set<Commande> commandes ) {
        this.nom = nom;
        this.prenom = prenom;
        this.adresse = adresse;
        this.telephone = telephone;
        this.email = email;
        this.image = image;
        this.commandes = commandes;
    }

    @Id
    @GeneratedValue( strategy = IDENTITY )

    @Column( name = "id", unique = true, nullable = false )
    public Integer getId() {
        return this.id;
    }

    public void setId( Integer id ) {
        this.id = id;
    }

    @Column( name = "nom", nullable = false, length = 20 )
    public String getNom() {
        return this.nom;
    }

    public void setNom( String nom ) {
        this.nom = nom;
    }

    @Column( name = "prenom", length = 20 )
    public String getPrenom() {
        return this.prenom;
    }

    public void setPrenom( String prenom ) {
        this.prenom = prenom;
    }

    @Column( name = "adresse", nullable = false, length = 200 )
    public String getAdresse() {
        return this.adresse;
    }

    public void setAdresse( String adresse ) {
        this.adresse = adresse;
    }

    @Column( name = "telephone", nullable = false, length = 10 )
    public String getTelephone() {
        return this.telephone;
    }

    public void setTelephone( String telephone ) {
        this.telephone = telephone;
    }

    @Column( name = "email", length = 60 )
    public String getEmail() {
        return this.email;
    }

    public void setEmail( String email ) {
        this.email = email;
    }

    @Column( name = "image", length = 200 )
    public String getImage() {
        return this.image;
    }

    public void setImage( String image ) {
        this.image = image;
    }

    @OneToMany( fetch = FetchType.LAZY, mappedBy = "client" )
    public Set<Commande> getCommandes() {
        return this.commandes;
    }

    public void setCommandes( Set<Commande> commandes ) {
        this.commandes = commandes;
    }

}
