package com.client.commande.ClientCommandeGestion.entity;
// Generated 4 juil. 2017 15:35:42 by Hibernate Tools 5.2.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Commande generated by hbm2java
 */
@Entity
@Table( name = "commande", catalog = "mybdd" )
public class Commande implements java.io.Serializable {

    private Integer id;
    private Client  client;
    private Date    date;
    private long    montant;
    private String  modePaiement;
    private String  statutPaiement;
    private String  modeLivraison;
    private String  statutLivraison;

    public Commande() {
    }

    public Commande( Date date, long montant, String modePaiement, String modeLivraison ) {
        this.date = date;
        this.montant = montant;
        this.modePaiement = modePaiement;
        this.modeLivraison = modeLivraison;
    }

    public Commande( Client client, Date date, long montant, String modePaiement, String statutPaiement,
            String modeLivraison, String statutLivraison ) {
        this.client = client;
        this.date = date;
        this.montant = montant;
        this.modePaiement = modePaiement;
        this.statutPaiement = statutPaiement;
        this.modeLivraison = modeLivraison;
        this.statutLivraison = statutLivraison;
    }

    @Id
    @GeneratedValue( strategy = IDENTITY )

    @Column( name = "id", unique = true, nullable = false )
    public Integer getId() {
        return this.id;
    }

    public void setId( Integer id ) {
        this.id = id;
    }

    @ManyToOne( fetch = FetchType.EAGER )
    @JoinColumn( name = "id_client" )
    public Client getClient() {
        return this.client;
    }

    public void setClient( Client client ) {
        this.client = client;
    }

    @Temporal( TemporalType.TIMESTAMP )
    @Column( name = "date", nullable = false, length = 19 )
    public Date getDate() {
        return this.date;
    }

    public void setDate( Date date ) {
        this.date = date;
    }

    @Column( name = "montant", nullable = false, precision = 11, scale = 0 )
    public long getMontant() {
        return this.montant;
    }

    public void setMontant( long montant ) {
        this.montant = montant;
    }

    @Column( name = "mode_paiement", nullable = false, length = 20 )
    public String getModePaiement() {
        return this.modePaiement;
    }

    public void setModePaiement( String modePaiement ) {
        this.modePaiement = modePaiement;
    }

    @Column( name = "statut_paiement", length = 20 )
    public String getStatutPaiement() {
        return this.statutPaiement;
    }

    public void setStatutPaiement( String statutPaiement ) {
        this.statutPaiement = statutPaiement;
    }

    @Column( name = "mode_livraison", nullable = false, length = 20 )
    public String getModeLivraison() {
        return this.modeLivraison;
    }

    public void setModeLivraison( String modeLivraison ) {
        this.modeLivraison = modeLivraison;
    }

    @Column( name = "statut_livraison", length = 20 )
    public String getStatutLivraison() {
        return this.statutLivraison;
    }

    public void setStatutLivraison( String statutLivraison ) {
        this.statutLivraison = statutLivraison;
    }

}
